# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 3.5
      env: TOX_ENV=py35-django2
    - python: 3.9
      env: TOX_ENV=py39-django51

# command to install dependencies
install:
  - pip install pip -U
  - pip install tox

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
